name: LiveBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SOLUTION_FILE_PATH: MetaHookSv/Plugins/ABCEnchance
  BUILD_CONFIGURATION: Release
  BUILD_CONFIGURATION_AVX: Release_AVX2

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    - name: Git Clone Metahook
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: hzqst/MetaHookSv
        path: MetaHookSv
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/ABCEnchance
        path: MetaHookSv/Plugins/ABCEnchance

    - name: Setup build env
      working-directory: MetaHookSv
      run: |
          git submodule update --init --recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Missing File
      working-directory: MetaHookSv/Plugins/ABCEnchance/src
      run: New-item ./Source/Utility/NeteaseApi.cpp;New-item ./Header/Utility/NeteaseApi.h

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION_AVX}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Move to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          Move-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance/Build/ABCEnchance.dll" -Destination "MetaHookSv/Plugins/ABCEnchance/Build/svencoop/metahook/plugins/ABCEnchance.dll"
          Move-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance/Build/ABCEnchance_AVX2.dll" -Destination "MetaHookSv/Plugins/ABCEnchance/Build/svencoop/metahook/plugins/ABCEnchance_AVX2.dll"
    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: MetaHookSv/Plugins/ABCEnchance/build/
          dest: ABCEnchance-windows-x86.zip
    - name: Current Time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY-MM-DD-HH-mm-ss
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ABCEnchance-${{steps.current-time.outputs.formattedTime}}.zip
        path: ABCEnchance-windows-x86.zip
