name: LiveBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SOLUTION_FILE_PATH: MetaHookSv/Plugins/ABCEnchance_CFefx
  BUILD_CONFIGURATION: Release
  BUILD_CONFIGURATION_AVX: Release_AVX2

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    - name: Git Clone Metahook
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: hzqst/MetaHookSv
        path: MetaHookSv
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: GAYd0N/ABCEnchance_CFefx
        path: MetaHookSv/Plugins/ABCEnchance_CFefx

    - name: Setup build env
      working-directory: MetaHookSv
      run: ./build-initdeps.bat
    
    - name: Setup glew
      working-directory: MetaHookSv
      run: ./build-glew.bat

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION_AVX}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Copy to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          Copy-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance_CFefx/Release/ABCEnchance.dll" -Destination "MetaHookSv/Plugins/ABCEnchance_CFefx/Build/ABCEnchance.dll"
          Copy-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance_CFefx/Release_AVX2/ABCEnchance.dll" -Destination "MetaHookSv/Plugins/ABCEnchance_CFefx/Build/ABCEnchance_AVX2.dll"
    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: MetaHookSv/Plugins/ABCEnchance_CFefx/build/
          dest: ABCEnchance-windows-x86.zip
    - name: Current Time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY-MM-DD-HH-mm-ss
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ABCEnchance-${{steps.current-time.outputs.formattedTime}}.zip
        path: ABCEnchance-windows-x86.zip
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 10

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: !cancelled()
      with:
        keep_latest: 10
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}