name: Build

on:
  push:
    tags:
    - 'v*'
    
env:
  SOLUTION_FILE_PATH: MetaHookSv/Plugins/ABCEnchance
  BUILD_CONFIGURATION: Release
  BUILD_CONFIGURATION_AVX: Release_AVX2

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    - name: Git Clone Metahook
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: hzqst/MetaHookSv
        path: MetaHookSv
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/ABCEnchance
        path: MetaHookSv/Plugins/ABCEnchance

    - name: Setup build env
      working-directory: MetaHookSv
      run: |
          git submodule update --init --recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Missing File
      working-directory: MetaHookSv/Plugins/ABCEnchance/src
      run: New-item ./Source/Utility/NeteaseApi.cpp;New-item ./Header/Utility/NeteaseApi.h

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION_AVX}} ${{env.SOLUTION_FILE_PATH}}

    - name: Build Installer
      working-directory: MetaHookSv/Plugins/ABCEnchance/ABCEnchanceInstaller
      run: dotnet publish -p:PublishProfile=FolderProfile
    
    - name: Move to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          Move-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance/Build/ABCEnchance.dll" -Destination "MetaHookSv/Plugins/ABCEnchance/Build/svencoop/metahook/plugins/ABCEnchance.dll"
          Move-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance/Build/ABCEnchance_AVX2.dll" -Destination "MetaHookSv/Plugins/ABCEnchance/Build/svencoop/metahook/plugins/ABCEnchance_AVX2.dll"
          Move-Item -Force -Path "MetaHookSv/Plugins/ABCEnchance/ABCEnchanceInstaller/bin/publish/ABCEnchanceInstaller.exe" -Destination "MetaHookSv/Plugins/ABCEnchance/Build/Installer.exe"

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: MetaHookSv/Plugins/ABCEnchance/build/
          dest: ABCEnchance-windows-x86.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: ABCEnchance-${{ github.ref }}
          files: |
            ABCEnchance-windows-x86.zip
