name: Build

on:
  push:
    tags:
    - 'v*'
    
env:
  SOLUTION_FILE_PATH: MetaHookSv/Plugins/ABCEnchance
  BUILD_CONFIGURATION: Release
  BUILD_CONFIGURATION_AVX: Release_AVX2

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    
    - uses: hzqst/checkout@v2.3.4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Init dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive
      shell: cmd

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /t:ABCEnchance
      
    - name: Build AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION_AVX}} /t:ABCEnchance

    - name: Build Installer
      working-directory: ABCEnchanceInstaller
      run: dotnet publish -p:PublishProfile=FolderProfile
    
    - name: Move to build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          Move-Item -Force -Path "Build/ABCEnchance.dll" -Destination "Build/svencoop/metahook/plugins/ABCEnchance.dll"
          Move-Item -Force -Path "Build/ABCEnchance_AVX2.dll" -Destination "Build/svencoop/metahook/plugins/ABCEnchance_AVX2.dll"
          Move-Item -Force -Path "ABCEnchanceInstaller/bin/publish/ABCEnchanceInstaller.exe" -Destination "Build/Installer.exe"

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: build/
          dest: ABCEnchance-windows-x86.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: ABCEnchance-${{ github.ref }}
          files: |
            ABCEnchance-windows-x86.zip
